[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
crossterm = "0.29.0"
fern = "0.7.1"
log = "0.4.28"
rand = "0.9.2"
rusqlite = "0.31.0" # Use the latest version available
thiserror = "2.0.17"
